/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdvancedRouteImport } from './routes/advanced'
import { Route as ContentRouteImport } from './routes/content'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as FactsRouteImport } from './routes/facts'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as CheckpointsCheckpointIdRouteImport } from './routes/checkpoints.$checkpointId'
import { Route as DemoPdfProofRouteImport } from './routes/demo.pdf-proof'
import { Route as DemoVisualEditorRouteImport } from './routes/demo.visual-editor'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as FactsImportRouteImport } from './routes/facts_.import'
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes.$resumeId'
import { Route as SourceRefinementsTaskIdRouteImport } from './routes/source-refinements.$taskId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ContextsRouteImport } from './routes/api/v1/contexts'
import { Route as ApiV1DuplicatesRouteImport } from './routes/api/v1/duplicates'
import { Route as ApiV1EvidenceRouteImport } from './routes/api/v1/evidence'
import { Route as ApiV1JobsRouteImport } from './routes/api/v1/jobs'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1SourcesRouteImport } from './routes/api/v1/sources'
import { Route as ApiV2ContentRouteImport } from './routes/api/v2/content'
import { Route as ApiV2ContextsRouteImport } from './routes/api/v2/contexts'
import { Route as ApiV2FactsRouteImport } from './routes/api/v2/facts'
import { Route as ApiV2ResumesRouteImport } from './routes/api/v2/resumes'
import { Route as ApiV2SourcesRouteImport } from './routes/api/v2/sources'
import { Route as ApiV2TemplatesRouteImport } from './routes/api/v2/templates'
import { Route as ApiV2VersionsRouteImport } from './routes/api/v2/versions'
import { Route as ApiArtifactsOperationIdKindRouteImport } from './routes/api/artifacts/$operationId.$kind'
import { Route as ApiV1EvidenceClaimIdRouteImport } from './routes/api/v1/evidence.$claimId'
import { Route as ApiV1EvidenceImportRouteImport } from './routes/api/v1/evidence.import'
import { Route as ApiV1JobsJobIdRouteImport } from './routes/api/v1/jobs.$jobId'
import { Route as ApiV1JobsImportsRouteImport } from './routes/api/v1/jobs.imports'
import { Route as ApiV1SourcesSourceIdRouteImport } from './routes/api/v1/sources.$sourceId'
import { Route as ApiV2ContentIdRouteImport } from './routes/api/v2/content.$id'
import { Route as ApiV2ContextsIdRouteImport } from './routes/api/v2/contexts.$id'
import { Route as ApiV2FactsIdRouteImport } from './routes/api/v2/facts.$id'
import { Route as ApiV2FactsImportRouteImport } from './routes/api/v2/facts.import'
import { Route as ApiV2ResumesIdRouteImport } from './routes/api/v2/resumes.$id'
import { Route as ApiV2TemplatesIdRouteImport } from './routes/api/v2/templates.$id'
import { Route as ApiV2VersionsIdRouteImport } from './routes/api/v2/versions.$id'
import { Route as ApiTemplateArtifactsValidationIdFixtureIdKindRouteImport } from './routes/api/template-artifacts/$validationId.$fixtureId.$kind'
import { Route as ApiTemplateProposalsTaskIdOperationIdKindRouteImport } from './routes/api/template-proposals/$taskId.$operationId.$kind'
import { Route as ApiTemplateScoresRunIdFixtureIdKindRouteImport } from './routes/api/template-scores/$runId.$fixtureId.$kind'
import { Route as ApiV1JobsImportsImportIdRouteImport } from './routes/api/v1/jobs.imports.$importId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvancedRoute = AdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FactsRoute = FactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsCheckpointIdRoute = CheckpointsCheckpointIdRouteImport.update({
  id: '/checkpoints/$checkpointId',
  path: '/checkpoints/$checkpointId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPdfProofRoute = DemoPdfProofRouteImport.update({
  id: '/demo/pdf-proof',
  path: '/demo/pdf-proof',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoVisualEditorRoute = DemoVisualEditorRouteImport.update({
  id: '/demo/visual-editor',
  path: '/demo/visual-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRoute,
} as any)
const FactsImportRoute = FactsImportRouteImport.update({
  id: '/facts_/import',
  path: '/facts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceRefinementsTaskIdRoute = SourceRefinementsTaskIdRouteImport.update({
  id: '/source-refinements/$taskId',
  path: '/source-refinements/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContextsRoute = ApiV1ContextsRouteImport.update({
  id: '/api/v1/contexts',
  path: '/api/v1/contexts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DuplicatesRoute = ApiV1DuplicatesRouteImport.update({
  id: '/api/v1/duplicates',
  path: '/api/v1/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EvidenceRoute = ApiV1EvidenceRouteImport.update({
  id: '/api/v1/evidence',
  path: '/api/v1/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JobsRoute = ApiV1JobsRouteImport.update({
  id: '/api/v1/jobs',
  path: '/api/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SourcesRoute = ApiV1SourcesRouteImport.update({
  id: '/api/v1/sources',
  path: '/api/v1/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2ContentRoute = ApiV2ContentRouteImport.update({
  id: '/api/v2/content',
  path: '/api/v2/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2ContextsRoute = ApiV2ContextsRouteImport.update({
  id: '/api/v2/contexts',
  path: '/api/v2/contexts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2FactsRoute = ApiV2FactsRouteImport.update({
  id: '/api/v2/facts',
  path: '/api/v2/facts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2ResumesRoute = ApiV2ResumesRouteImport.update({
  id: '/api/v2/resumes',
  path: '/api/v2/resumes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2SourcesRoute = ApiV2SourcesRouteImport.update({
  id: '/api/v2/sources',
  path: '/api/v2/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2TemplatesRoute = ApiV2TemplatesRouteImport.update({
  id: '/api/v2/templates',
  path: '/api/v2/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV2VersionsRoute = ApiV2VersionsRouteImport.update({
  id: '/api/v2/versions',
  path: '/api/v2/versions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsOperationIdKindRoute =
  ApiArtifactsOperationIdKindRouteImport.update({
    id: '/api/artifacts/$operationId/$kind',
    path: '/api/artifacts/$operationId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1EvidenceClaimIdRoute = ApiV1EvidenceClaimIdRouteImport.update({
  id: '/$claimId',
  path: '/$claimId',
  getParentRoute: () => ApiV1EvidenceRoute,
} as any)
const ApiV1EvidenceImportRoute = ApiV1EvidenceImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiV1EvidenceRoute,
} as any)
const ApiV1JobsJobIdRoute = ApiV1JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiV1JobsRoute,
} as any)
const ApiV1JobsImportsRoute = ApiV1JobsImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => ApiV1JobsRoute,
} as any)
const ApiV1SourcesSourceIdRoute = ApiV1SourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => ApiV1SourcesRoute,
} as any)
const ApiV2ContentIdRoute = ApiV2ContentIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV2ContentRoute,
} as any)
const ApiV2ContextsIdRoute = ApiV2ContextsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV2ContextsRoute,
} as any)
const ApiV2FactsIdRoute = ApiV2FactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV2FactsRoute,
} as any)
const ApiV2FactsImportRoute = ApiV2FactsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiV2FactsRoute,
} as any)
const ApiV2ResumesIdRoute = ApiV2ResumesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV2ResumesRoute,
} as any)
const ApiV2TemplatesIdRoute = ApiV2TemplatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV2TemplatesRoute,
} as any)
const ApiV2VersionsIdRoute = ApiV2VersionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV2VersionsRoute,
} as any)
const ApiTemplateArtifactsValidationIdFixtureIdKindRoute =
  ApiTemplateArtifactsValidationIdFixtureIdKindRouteImport.update({
    id: '/api/template-artifacts/$validationId/$fixtureId/$kind',
    path: '/api/template-artifacts/$validationId/$fixtureId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTemplateProposalsTaskIdOperationIdKindRoute =
  ApiTemplateProposalsTaskIdOperationIdKindRouteImport.update({
    id: '/api/template-proposals/$taskId/$operationId/$kind',
    path: '/api/template-proposals/$taskId/$operationId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTemplateScoresRunIdFixtureIdKindRoute =
  ApiTemplateScoresRunIdFixtureIdKindRouteImport.update({
    id: '/api/template-scores/$runId/$fixtureId/$kind',
    path: '/api/template-scores/$runId/$fixtureId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1JobsImportsImportIdRoute =
  ApiV1JobsImportsImportIdRouteImport.update({
    id: '/$importId',
    path: '/$importId',
    getParentRoute: () => ApiV1JobsImportsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advanced': typeof AdvancedRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRouteWithChildren
  '/evidence': typeof EvidenceRoute
  '/facts': typeof FactsRoute
  '/feedback': typeof FeedbackRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/trash': typeof TrashRoute
  '/checkpoints/$checkpointId': typeof CheckpointsCheckpointIdRoute
  '/demo/pdf-proof': typeof DemoPdfProofRoute
  '/demo/visual-editor': typeof DemoVisualEditorRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/facts/import': typeof FactsImportRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/source-refinements/$taskId': typeof SourceRefinementsTaskIdRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/contexts': typeof ApiV1ContextsRoute
  '/api/v1/duplicates': typeof ApiV1DuplicatesRoute
  '/api/v1/evidence': typeof ApiV1EvidenceRouteWithChildren
  '/api/v1/jobs': typeof ApiV1JobsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sources': typeof ApiV1SourcesRouteWithChildren
  '/api/v2/content': typeof ApiV2ContentRouteWithChildren
  '/api/v2/contexts': typeof ApiV2ContextsRouteWithChildren
  '/api/v2/facts': typeof ApiV2FactsRouteWithChildren
  '/api/v2/resumes': typeof ApiV2ResumesRouteWithChildren
  '/api/v2/sources': typeof ApiV2SourcesRoute
  '/api/v2/templates': typeof ApiV2TemplatesRouteWithChildren
  '/api/v2/versions': typeof ApiV2VersionsRouteWithChildren
  '/api/artifacts/$operationId/$kind': typeof ApiArtifactsOperationIdKindRoute
  '/api/v1/evidence/$claimId': typeof ApiV1EvidenceClaimIdRoute
  '/api/v1/evidence/import': typeof ApiV1EvidenceImportRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/jobs/imports': typeof ApiV1JobsImportsRouteWithChildren
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
  '/api/v2/content/$id': typeof ApiV2ContentIdRoute
  '/api/v2/contexts/$id': typeof ApiV2ContextsIdRoute
  '/api/v2/facts/$id': typeof ApiV2FactsIdRoute
  '/api/v2/facts/import': typeof ApiV2FactsImportRoute
  '/api/v2/resumes/$id': typeof ApiV2ResumesIdRoute
  '/api/v2/templates/$id': typeof ApiV2TemplatesIdRoute
  '/api/v2/versions/$id': typeof ApiV2VersionsIdRoute
  '/api/template-artifacts/$validationId/$fixtureId/$kind': typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  '/api/template-proposals/$taskId/$operationId/$kind': typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
  '/api/template-scores/$runId/$fixtureId/$kind': typeof ApiTemplateScoresRunIdFixtureIdKindRoute
  '/api/v1/jobs/imports/$importId': typeof ApiV1JobsImportsImportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advanced': typeof AdvancedRoute
  '/content': typeof ContentRoute
  '/evidence': typeof EvidenceRoute
  '/facts': typeof FactsRoute
  '/feedback': typeof FeedbackRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/trash': typeof TrashRoute
  '/checkpoints/$checkpointId': typeof CheckpointsCheckpointIdRoute
  '/demo/pdf-proof': typeof DemoPdfProofRoute
  '/demo/visual-editor': typeof DemoVisualEditorRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/facts/import': typeof FactsImportRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/source-refinements/$taskId': typeof SourceRefinementsTaskIdRoute
  '/docs': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/contexts': typeof ApiV1ContextsRoute
  '/api/v1/duplicates': typeof ApiV1DuplicatesRoute
  '/api/v1/evidence': typeof ApiV1EvidenceRouteWithChildren
  '/api/v1/jobs': typeof ApiV1JobsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sources': typeof ApiV1SourcesRouteWithChildren
  '/api/v2/content': typeof ApiV2ContentRouteWithChildren
  '/api/v2/contexts': typeof ApiV2ContextsRouteWithChildren
  '/api/v2/facts': typeof ApiV2FactsRouteWithChildren
  '/api/v2/resumes': typeof ApiV2ResumesRouteWithChildren
  '/api/v2/sources': typeof ApiV2SourcesRoute
  '/api/v2/templates': typeof ApiV2TemplatesRouteWithChildren
  '/api/v2/versions': typeof ApiV2VersionsRouteWithChildren
  '/api/artifacts/$operationId/$kind': typeof ApiArtifactsOperationIdKindRoute
  '/api/v1/evidence/$claimId': typeof ApiV1EvidenceClaimIdRoute
  '/api/v1/evidence/import': typeof ApiV1EvidenceImportRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/jobs/imports': typeof ApiV1JobsImportsRouteWithChildren
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
  '/api/v2/content/$id': typeof ApiV2ContentIdRoute
  '/api/v2/contexts/$id': typeof ApiV2ContextsIdRoute
  '/api/v2/facts/$id': typeof ApiV2FactsIdRoute
  '/api/v2/facts/import': typeof ApiV2FactsImportRoute
  '/api/v2/resumes/$id': typeof ApiV2ResumesIdRoute
  '/api/v2/templates/$id': typeof ApiV2TemplatesIdRoute
  '/api/v2/versions/$id': typeof ApiV2VersionsIdRoute
  '/api/template-artifacts/$validationId/$fixtureId/$kind': typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  '/api/template-proposals/$taskId/$operationId/$kind': typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
  '/api/template-scores/$runId/$fixtureId/$kind': typeof ApiTemplateScoresRunIdFixtureIdKindRoute
  '/api/v1/jobs/imports/$importId': typeof ApiV1JobsImportsImportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/advanced': typeof AdvancedRoute
  '/content': typeof ContentRoute
  '/docs': typeof DocsRouteWithChildren
  '/evidence': typeof EvidenceRoute
  '/facts': typeof FactsRoute
  '/feedback': typeof FeedbackRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/runtime': typeof RuntimeRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/trash': typeof TrashRoute
  '/checkpoints/$checkpointId': typeof CheckpointsCheckpointIdRoute
  '/demo/pdf-proof': typeof DemoPdfProofRoute
  '/demo/visual-editor': typeof DemoVisualEditorRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/facts_/import': typeof FactsImportRoute
  '/jobs_/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/source-refinements/$taskId': typeof SourceRefinementsTaskIdRoute
  '/docs/': typeof DocsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/contexts': typeof ApiV1ContextsRoute
  '/api/v1/duplicates': typeof ApiV1DuplicatesRoute
  '/api/v1/evidence': typeof ApiV1EvidenceRouteWithChildren
  '/api/v1/jobs': typeof ApiV1JobsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sources': typeof ApiV1SourcesRouteWithChildren
  '/api/v2/content': typeof ApiV2ContentRouteWithChildren
  '/api/v2/contexts': typeof ApiV2ContextsRouteWithChildren
  '/api/v2/facts': typeof ApiV2FactsRouteWithChildren
  '/api/v2/resumes': typeof ApiV2ResumesRouteWithChildren
  '/api/v2/sources': typeof ApiV2SourcesRoute
  '/api/v2/templates': typeof ApiV2TemplatesRouteWithChildren
  '/api/v2/versions': typeof ApiV2VersionsRouteWithChildren
  '/api/artifacts/$operationId/$kind': typeof ApiArtifactsOperationIdKindRoute
  '/api/v1/evidence/$claimId': typeof ApiV1EvidenceClaimIdRoute
  '/api/v1/evidence/import': typeof ApiV1EvidenceImportRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/jobs/imports': typeof ApiV1JobsImportsRouteWithChildren
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
  '/api/v2/content/$id': typeof ApiV2ContentIdRoute
  '/api/v2/contexts/$id': typeof ApiV2ContextsIdRoute
  '/api/v2/facts/$id': typeof ApiV2FactsIdRoute
  '/api/v2/facts/import': typeof ApiV2FactsImportRoute
  '/api/v2/resumes/$id': typeof ApiV2ResumesIdRoute
  '/api/v2/templates/$id': typeof ApiV2TemplatesIdRoute
  '/api/v2/versions/$id': typeof ApiV2VersionsIdRoute
  '/api/template-artifacts/$validationId/$fixtureId/$kind': typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  '/api/template-proposals/$taskId/$operationId/$kind': typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
  '/api/template-scores/$runId/$fixtureId/$kind': typeof ApiTemplateScoresRunIdFixtureIdKindRoute
  '/api/v1/jobs/imports/$importId': typeof ApiV1JobsImportsImportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/advanced'
    | '/content'
    | '/docs'
    | '/evidence'
    | '/facts'
    | '/feedback'
    | '/jobs'
    | '/library'
    | '/mcp'
    | '/reset-password'
    | '/runtime'
    | '/settings'
    | '/sign-in'
    | '/sources'
    | '/templates'
    | '/trash'
    | '/checkpoints/$checkpointId'
    | '/demo/pdf-proof'
    | '/demo/visual-editor'
    | '/docs/$slug'
    | '/facts/import'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/source-refinements/$taskId'
    | '/docs/'
    | '/api/auth/$'
    | '/api/v1/contexts'
    | '/api/v1/duplicates'
    | '/api/v1/evidence'
    | '/api/v1/jobs'
    | '/api/v1/me'
    | '/api/v1/sources'
    | '/api/v2/content'
    | '/api/v2/contexts'
    | '/api/v2/facts'
    | '/api/v2/resumes'
    | '/api/v2/sources'
    | '/api/v2/templates'
    | '/api/v2/versions'
    | '/api/artifacts/$operationId/$kind'
    | '/api/v1/evidence/$claimId'
    | '/api/v1/evidence/import'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/jobs/imports'
    | '/api/v1/sources/$sourceId'
    | '/api/v2/content/$id'
    | '/api/v2/contexts/$id'
    | '/api/v2/facts/$id'
    | '/api/v2/facts/import'
    | '/api/v2/resumes/$id'
    | '/api/v2/templates/$id'
    | '/api/v2/versions/$id'
    | '/api/template-artifacts/$validationId/$fixtureId/$kind'
    | '/api/template-proposals/$taskId/$operationId/$kind'
    | '/api/template-scores/$runId/$fixtureId/$kind'
    | '/api/v1/jobs/imports/$importId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/advanced'
    | '/content'
    | '/evidence'
    | '/facts'
    | '/feedback'
    | '/jobs'
    | '/library'
    | '/mcp'
    | '/reset-password'
    | '/runtime'
    | '/settings'
    | '/sign-in'
    | '/sources'
    | '/templates'
    | '/trash'
    | '/checkpoints/$checkpointId'
    | '/demo/pdf-proof'
    | '/demo/visual-editor'
    | '/docs/$slug'
    | '/facts/import'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/source-refinements/$taskId'
    | '/docs'
    | '/api/auth/$'
    | '/api/v1/contexts'
    | '/api/v1/duplicates'
    | '/api/v1/evidence'
    | '/api/v1/jobs'
    | '/api/v1/me'
    | '/api/v1/sources'
    | '/api/v2/content'
    | '/api/v2/contexts'
    | '/api/v2/facts'
    | '/api/v2/resumes'
    | '/api/v2/sources'
    | '/api/v2/templates'
    | '/api/v2/versions'
    | '/api/artifacts/$operationId/$kind'
    | '/api/v1/evidence/$claimId'
    | '/api/v1/evidence/import'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/jobs/imports'
    | '/api/v1/sources/$sourceId'
    | '/api/v2/content/$id'
    | '/api/v2/contexts/$id'
    | '/api/v2/facts/$id'
    | '/api/v2/facts/import'
    | '/api/v2/resumes/$id'
    | '/api/v2/templates/$id'
    | '/api/v2/versions/$id'
    | '/api/template-artifacts/$validationId/$fixtureId/$kind'
    | '/api/template-proposals/$taskId/$operationId/$kind'
    | '/api/template-scores/$runId/$fixtureId/$kind'
    | '/api/v1/jobs/imports/$importId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/advanced'
    | '/content'
    | '/docs'
    | '/evidence'
    | '/facts'
    | '/feedback'
    | '/jobs'
    | '/library'
    | '/mcp'
    | '/reset-password'
    | '/runtime'
    | '/settings'
    | '/sign-in'
    | '/sources'
    | '/templates'
    | '/trash'
    | '/checkpoints/$checkpointId'
    | '/demo/pdf-proof'
    | '/demo/visual-editor'
    | '/docs/$slug'
    | '/facts_/import'
    | '/jobs_/$jobId'
    | '/resumes/$resumeId'
    | '/source-refinements/$taskId'
    | '/docs/'
    | '/api/auth/$'
    | '/api/v1/contexts'
    | '/api/v1/duplicates'
    | '/api/v1/evidence'
    | '/api/v1/jobs'
    | '/api/v1/me'
    | '/api/v1/sources'
    | '/api/v2/content'
    | '/api/v2/contexts'
    | '/api/v2/facts'
    | '/api/v2/resumes'
    | '/api/v2/sources'
    | '/api/v2/templates'
    | '/api/v2/versions'
    | '/api/artifacts/$operationId/$kind'
    | '/api/v1/evidence/$claimId'
    | '/api/v1/evidence/import'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/jobs/imports'
    | '/api/v1/sources/$sourceId'
    | '/api/v2/content/$id'
    | '/api/v2/contexts/$id'
    | '/api/v2/facts/$id'
    | '/api/v2/facts/import'
    | '/api/v2/resumes/$id'
    | '/api/v2/templates/$id'
    | '/api/v2/versions/$id'
    | '/api/template-artifacts/$validationId/$fixtureId/$kind'
    | '/api/template-proposals/$taskId/$operationId/$kind'
    | '/api/template-scores/$runId/$fixtureId/$kind'
    | '/api/v1/jobs/imports/$importId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdvancedRoute: typeof AdvancedRoute
  ContentRoute: typeof ContentRoute
  DocsRoute: typeof DocsRouteWithChildren
  EvidenceRoute: typeof EvidenceRoute
  FactsRoute: typeof FactsRoute
  FeedbackRoute: typeof FeedbackRoute
  JobsRoute: typeof JobsRoute
  LibraryRoute: typeof LibraryRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RuntimeRoute: typeof RuntimeRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SourcesRoute: typeof SourcesRoute
  TemplatesRoute: typeof TemplatesRoute
  TrashRoute: typeof TrashRoute
  CheckpointsCheckpointIdRoute: typeof CheckpointsCheckpointIdRoute
  DemoPdfProofRoute: typeof DemoPdfProofRoute
  DemoVisualEditorRoute: typeof DemoVisualEditorRoute
  FactsImportRoute: typeof FactsImportRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRoute
  SourceRefinementsTaskIdRoute: typeof SourceRefinementsTaskIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ContextsRoute: typeof ApiV1ContextsRoute
  ApiV1DuplicatesRoute: typeof ApiV1DuplicatesRoute
  ApiV1EvidenceRoute: typeof ApiV1EvidenceRouteWithChildren
  ApiV1JobsRoute: typeof ApiV1JobsRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1SourcesRoute: typeof ApiV1SourcesRouteWithChildren
  ApiV2ContentRoute: typeof ApiV2ContentRouteWithChildren
  ApiV2ContextsRoute: typeof ApiV2ContextsRouteWithChildren
  ApiV2FactsRoute: typeof ApiV2FactsRouteWithChildren
  ApiV2ResumesRoute: typeof ApiV2ResumesRouteWithChildren
  ApiV2SourcesRoute: typeof ApiV2SourcesRoute
  ApiV2TemplatesRoute: typeof ApiV2TemplatesRouteWithChildren
  ApiV2VersionsRoute: typeof ApiV2VersionsRouteWithChildren
  ApiArtifactsOperationIdKindRoute: typeof ApiArtifactsOperationIdKindRoute
  ApiTemplateArtifactsValidationIdFixtureIdKindRoute: typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  ApiTemplateProposalsTaskIdOperationIdKindRoute: typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
  ApiTemplateScoresRunIdFixtureIdKindRoute: typeof ApiTemplateScoresRunIdFixtureIdKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advanced': {
      id: '/advanced'
      path: '/advanced'
      fullPath: '/advanced'
      preLoaderRoute: typeof AdvancedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facts': {
      id: '/facts'
      path: '/facts'
      fullPath: '/facts'
      preLoaderRoute: typeof FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints/$checkpointId': {
      id: '/checkpoints/$checkpointId'
      path: '/checkpoints/$checkpointId'
      fullPath: '/checkpoints/$checkpointId'
      preLoaderRoute: typeof CheckpointsCheckpointIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pdf-proof': {
      id: '/demo/pdf-proof'
      path: '/demo/pdf-proof'
      fullPath: '/demo/pdf-proof'
      preLoaderRoute: typeof DemoPdfProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/visual-editor': {
      id: '/demo/visual-editor'
      path: '/demo/visual-editor'
      fullPath: '/demo/visual-editor'
      preLoaderRoute: typeof DemoVisualEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRoute
    }
    '/facts_/import': {
      id: '/facts_/import'
      path: '/facts/import'
      fullPath: '/facts/import'
      preLoaderRoute: typeof FactsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-refinements/$taskId': {
      id: '/source-refinements/$taskId'
      path: '/source-refinements/$taskId'
      fullPath: '/source-refinements/$taskId'
      preLoaderRoute: typeof SourceRefinementsTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contexts': {
      id: '/api/v1/contexts'
      path: '/api/v1/contexts'
      fullPath: '/api/v1/contexts'
      preLoaderRoute: typeof ApiV1ContextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/duplicates': {
      id: '/api/v1/duplicates'
      path: '/api/v1/duplicates'
      fullPath: '/api/v1/duplicates'
      preLoaderRoute: typeof ApiV1DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evidence': {
      id: '/api/v1/evidence'
      path: '/api/v1/evidence'
      fullPath: '/api/v1/evidence'
      preLoaderRoute: typeof ApiV1EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs': {
      id: '/api/v1/jobs'
      path: '/api/v1/jobs'
      fullPath: '/api/v1/jobs'
      preLoaderRoute: typeof ApiV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sources': {
      id: '/api/v1/sources'
      path: '/api/v1/sources'
      fullPath: '/api/v1/sources'
      preLoaderRoute: typeof ApiV1SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/content': {
      id: '/api/v2/content'
      path: '/api/v2/content'
      fullPath: '/api/v2/content'
      preLoaderRoute: typeof ApiV2ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/contexts': {
      id: '/api/v2/contexts'
      path: '/api/v2/contexts'
      fullPath: '/api/v2/contexts'
      preLoaderRoute: typeof ApiV2ContextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/facts': {
      id: '/api/v2/facts'
      path: '/api/v2/facts'
      fullPath: '/api/v2/facts'
      preLoaderRoute: typeof ApiV2FactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/resumes': {
      id: '/api/v2/resumes'
      path: '/api/v2/resumes'
      fullPath: '/api/v2/resumes'
      preLoaderRoute: typeof ApiV2ResumesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/sources': {
      id: '/api/v2/sources'
      path: '/api/v2/sources'
      fullPath: '/api/v2/sources'
      preLoaderRoute: typeof ApiV2SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/templates': {
      id: '/api/v2/templates'
      path: '/api/v2/templates'
      fullPath: '/api/v2/templates'
      preLoaderRoute: typeof ApiV2TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v2/versions': {
      id: '/api/v2/versions'
      path: '/api/v2/versions'
      fullPath: '/api/v2/versions'
      preLoaderRoute: typeof ApiV2VersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts/$operationId/$kind': {
      id: '/api/artifacts/$operationId/$kind'
      path: '/api/artifacts/$operationId/$kind'
      fullPath: '/api/artifacts/$operationId/$kind'
      preLoaderRoute: typeof ApiArtifactsOperationIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evidence/$claimId': {
      id: '/api/v1/evidence/$claimId'
      path: '/$claimId'
      fullPath: '/api/v1/evidence/$claimId'
      preLoaderRoute: typeof ApiV1EvidenceClaimIdRouteImport
      parentRoute: typeof ApiV1EvidenceRoute
    }
    '/api/v1/evidence/import': {
      id: '/api/v1/evidence/import'
      path: '/import'
      fullPath: '/api/v1/evidence/import'
      preLoaderRoute: typeof ApiV1EvidenceImportRouteImport
      parentRoute: typeof ApiV1EvidenceRoute
    }
    '/api/v1/jobs/$jobId': {
      id: '/api/v1/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiV1JobsJobIdRouteImport
      parentRoute: typeof ApiV1JobsRoute
    }
    '/api/v1/jobs/imports': {
      id: '/api/v1/jobs/imports'
      path: '/imports'
      fullPath: '/api/v1/jobs/imports'
      preLoaderRoute: typeof ApiV1JobsImportsRouteImport
      parentRoute: typeof ApiV1JobsRoute
    }
    '/api/v1/sources/$sourceId': {
      id: '/api/v1/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/api/v1/sources/$sourceId'
      preLoaderRoute: typeof ApiV1SourcesSourceIdRouteImport
      parentRoute: typeof ApiV1SourcesRoute
    }
    '/api/v2/content/$id': {
      id: '/api/v2/content/$id'
      path: '/$id'
      fullPath: '/api/v2/content/$id'
      preLoaderRoute: typeof ApiV2ContentIdRouteImport
      parentRoute: typeof ApiV2ContentRoute
    }
    '/api/v2/contexts/$id': {
      id: '/api/v2/contexts/$id'
      path: '/$id'
      fullPath: '/api/v2/contexts/$id'
      preLoaderRoute: typeof ApiV2ContextsIdRouteImport
      parentRoute: typeof ApiV2ContextsRoute
    }
    '/api/v2/facts/$id': {
      id: '/api/v2/facts/$id'
      path: '/$id'
      fullPath: '/api/v2/facts/$id'
      preLoaderRoute: typeof ApiV2FactsIdRouteImport
      parentRoute: typeof ApiV2FactsRoute
    }
    '/api/v2/facts/import': {
      id: '/api/v2/facts/import'
      path: '/import'
      fullPath: '/api/v2/facts/import'
      preLoaderRoute: typeof ApiV2FactsImportRouteImport
      parentRoute: typeof ApiV2FactsRoute
    }
    '/api/v2/resumes/$id': {
      id: '/api/v2/resumes/$id'
      path: '/$id'
      fullPath: '/api/v2/resumes/$id'
      preLoaderRoute: typeof ApiV2ResumesIdRouteImport
      parentRoute: typeof ApiV2ResumesRoute
    }
    '/api/v2/templates/$id': {
      id: '/api/v2/templates/$id'
      path: '/$id'
      fullPath: '/api/v2/templates/$id'
      preLoaderRoute: typeof ApiV2TemplatesIdRouteImport
      parentRoute: typeof ApiV2TemplatesRoute
    }
    '/api/v2/versions/$id': {
      id: '/api/v2/versions/$id'
      path: '/$id'
      fullPath: '/api/v2/versions/$id'
      preLoaderRoute: typeof ApiV2VersionsIdRouteImport
      parentRoute: typeof ApiV2VersionsRoute
    }
    '/api/template-artifacts/$validationId/$fixtureId/$kind': {
      id: '/api/template-artifacts/$validationId/$fixtureId/$kind'
      path: '/api/template-artifacts/$validationId/$fixtureId/$kind'
      fullPath: '/api/template-artifacts/$validationId/$fixtureId/$kind'
      preLoaderRoute: typeof ApiTemplateArtifactsValidationIdFixtureIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/template-proposals/$taskId/$operationId/$kind': {
      id: '/api/template-proposals/$taskId/$operationId/$kind'
      path: '/api/template-proposals/$taskId/$operationId/$kind'
      fullPath: '/api/template-proposals/$taskId/$operationId/$kind'
      preLoaderRoute: typeof ApiTemplateProposalsTaskIdOperationIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/template-scores/$runId/$fixtureId/$kind': {
      id: '/api/template-scores/$runId/$fixtureId/$kind'
      path: '/api/template-scores/$runId/$fixtureId/$kind'
      fullPath: '/api/template-scores/$runId/$fixtureId/$kind'
      preLoaderRoute: typeof ApiTemplateScoresRunIdFixtureIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs/imports/$importId': {
      id: '/api/v1/jobs/imports/$importId'
      path: '/$importId'
      fullPath: '/api/v1/jobs/imports/$importId'
      preLoaderRoute: typeof ApiV1JobsImportsImportIdRouteImport
      parentRoute: typeof ApiV1JobsImportsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

interface ApiV1EvidenceRouteChildren {
  ApiV1EvidenceClaimIdRoute: typeof ApiV1EvidenceClaimIdRoute
  ApiV1EvidenceImportRoute: typeof ApiV1EvidenceImportRoute
}

const ApiV1EvidenceRouteChildren: ApiV1EvidenceRouteChildren = {
  ApiV1EvidenceClaimIdRoute: ApiV1EvidenceClaimIdRoute,
  ApiV1EvidenceImportRoute: ApiV1EvidenceImportRoute,
}

const ApiV1EvidenceRouteWithChildren = ApiV1EvidenceRoute._addFileChildren(
  ApiV1EvidenceRouteChildren,
)

interface ApiV1JobsImportsRouteChildren {
  ApiV1JobsImportsImportIdRoute: typeof ApiV1JobsImportsImportIdRoute
}

const ApiV1JobsImportsRouteChildren: ApiV1JobsImportsRouteChildren = {
  ApiV1JobsImportsImportIdRoute: ApiV1JobsImportsImportIdRoute,
}

const ApiV1JobsImportsRouteWithChildren =
  ApiV1JobsImportsRoute._addFileChildren(ApiV1JobsImportsRouteChildren)

interface ApiV1JobsRouteChildren {
  ApiV1JobsJobIdRoute: typeof ApiV1JobsJobIdRoute
  ApiV1JobsImportsRoute: typeof ApiV1JobsImportsRouteWithChildren
}

const ApiV1JobsRouteChildren: ApiV1JobsRouteChildren = {
  ApiV1JobsJobIdRoute: ApiV1JobsJobIdRoute,
  ApiV1JobsImportsRoute: ApiV1JobsImportsRouteWithChildren,
}

const ApiV1JobsRouteWithChildren = ApiV1JobsRoute._addFileChildren(
  ApiV1JobsRouteChildren,
)

interface ApiV1SourcesRouteChildren {
  ApiV1SourcesSourceIdRoute: typeof ApiV1SourcesSourceIdRoute
}

const ApiV1SourcesRouteChildren: ApiV1SourcesRouteChildren = {
  ApiV1SourcesSourceIdRoute: ApiV1SourcesSourceIdRoute,
}

const ApiV1SourcesRouteWithChildren = ApiV1SourcesRoute._addFileChildren(
  ApiV1SourcesRouteChildren,
)

interface ApiV2ContentRouteChildren {
  ApiV2ContentIdRoute: typeof ApiV2ContentIdRoute
}

const ApiV2ContentRouteChildren: ApiV2ContentRouteChildren = {
  ApiV2ContentIdRoute: ApiV2ContentIdRoute,
}

const ApiV2ContentRouteWithChildren = ApiV2ContentRoute._addFileChildren(
  ApiV2ContentRouteChildren,
)

interface ApiV2ContextsRouteChildren {
  ApiV2ContextsIdRoute: typeof ApiV2ContextsIdRoute
}

const ApiV2ContextsRouteChildren: ApiV2ContextsRouteChildren = {
  ApiV2ContextsIdRoute: ApiV2ContextsIdRoute,
}

const ApiV2ContextsRouteWithChildren = ApiV2ContextsRoute._addFileChildren(
  ApiV2ContextsRouteChildren,
)

interface ApiV2FactsRouteChildren {
  ApiV2FactsIdRoute: typeof ApiV2FactsIdRoute
  ApiV2FactsImportRoute: typeof ApiV2FactsImportRoute
}

const ApiV2FactsRouteChildren: ApiV2FactsRouteChildren = {
  ApiV2FactsIdRoute: ApiV2FactsIdRoute,
  ApiV2FactsImportRoute: ApiV2FactsImportRoute,
}

const ApiV2FactsRouteWithChildren = ApiV2FactsRoute._addFileChildren(
  ApiV2FactsRouteChildren,
)

interface ApiV2ResumesRouteChildren {
  ApiV2ResumesIdRoute: typeof ApiV2ResumesIdRoute
}

const ApiV2ResumesRouteChildren: ApiV2ResumesRouteChildren = {
  ApiV2ResumesIdRoute: ApiV2ResumesIdRoute,
}

const ApiV2ResumesRouteWithChildren = ApiV2ResumesRoute._addFileChildren(
  ApiV2ResumesRouteChildren,
)

interface ApiV2TemplatesRouteChildren {
  ApiV2TemplatesIdRoute: typeof ApiV2TemplatesIdRoute
}

const ApiV2TemplatesRouteChildren: ApiV2TemplatesRouteChildren = {
  ApiV2TemplatesIdRoute: ApiV2TemplatesIdRoute,
}

const ApiV2TemplatesRouteWithChildren = ApiV2TemplatesRoute._addFileChildren(
  ApiV2TemplatesRouteChildren,
)

interface ApiV2VersionsRouteChildren {
  ApiV2VersionsIdRoute: typeof ApiV2VersionsIdRoute
}

const ApiV2VersionsRouteChildren: ApiV2VersionsRouteChildren = {
  ApiV2VersionsIdRoute: ApiV2VersionsIdRoute,
}

const ApiV2VersionsRouteWithChildren = ApiV2VersionsRoute._addFileChildren(
  ApiV2VersionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdvancedRoute: AdvancedRoute,
  ContentRoute: ContentRoute,
  DocsRoute: DocsRouteWithChildren,
  EvidenceRoute: EvidenceRoute,
  FactsRoute: FactsRoute,
  FeedbackRoute: FeedbackRoute,
  JobsRoute: JobsRoute,
  LibraryRoute: LibraryRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RuntimeRoute: RuntimeRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SourcesRoute: SourcesRoute,
  TemplatesRoute: TemplatesRoute,
  TrashRoute: TrashRoute,
  CheckpointsCheckpointIdRoute: CheckpointsCheckpointIdRoute,
  DemoPdfProofRoute: DemoPdfProofRoute,
  DemoVisualEditorRoute: DemoVisualEditorRoute,
  FactsImportRoute: FactsImportRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResumesResumeIdRoute: ResumesResumeIdRoute,
  SourceRefinementsTaskIdRoute: SourceRefinementsTaskIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ContextsRoute: ApiV1ContextsRoute,
  ApiV1DuplicatesRoute: ApiV1DuplicatesRoute,
  ApiV1EvidenceRoute: ApiV1EvidenceRouteWithChildren,
  ApiV1JobsRoute: ApiV1JobsRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1SourcesRoute: ApiV1SourcesRouteWithChildren,
  ApiV2ContentRoute: ApiV2ContentRouteWithChildren,
  ApiV2ContextsRoute: ApiV2ContextsRouteWithChildren,
  ApiV2FactsRoute: ApiV2FactsRouteWithChildren,
  ApiV2ResumesRoute: ApiV2ResumesRouteWithChildren,
  ApiV2SourcesRoute: ApiV2SourcesRoute,
  ApiV2TemplatesRoute: ApiV2TemplatesRouteWithChildren,
  ApiV2VersionsRoute: ApiV2VersionsRouteWithChildren,
  ApiArtifactsOperationIdKindRoute: ApiArtifactsOperationIdKindRoute,
  ApiTemplateArtifactsValidationIdFixtureIdKindRoute:
    ApiTemplateArtifactsValidationIdFixtureIdKindRoute,
  ApiTemplateProposalsTaskIdOperationIdKindRoute:
    ApiTemplateProposalsTaskIdOperationIdKindRoute,
  ApiTemplateScoresRunIdFixtureIdKindRoute:
    ApiTemplateScoresRunIdFixtureIdKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
