/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as CheckpointsCheckpointIdRouteImport } from './routes/checkpoints.$checkpointId'
import { Route as JobsJobIdRouteImport } from './routes/jobs_.$jobId'
import { Route as ResumesResumeIdRouteImport } from './routes/resumes.$resumeId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1ContextsRouteImport } from './routes/api/v1/contexts'
import { Route as ApiV1DuplicatesRouteImport } from './routes/api/v1/duplicates'
import { Route as ApiV1EvidenceRouteImport } from './routes/api/v1/evidence'
import { Route as ApiV1JobsRouteImport } from './routes/api/v1/jobs'
import { Route as ApiV1MeRouteImport } from './routes/api/v1/me'
import { Route as ApiV1SourcesRouteImport } from './routes/api/v1/sources'
import { Route as ApiArtifactsOperationIdKindRouteImport } from './routes/api/artifacts/$operationId.$kind'
import { Route as ApiV1EvidenceClaimIdRouteImport } from './routes/api/v1/evidence.$claimId'
import { Route as ApiV1JobsJobIdRouteImport } from './routes/api/v1/jobs.$jobId'
import { Route as ApiV1SourcesSourceIdRouteImport } from './routes/api/v1/sources.$sourceId'
import { Route as ApiTemplateArtifactsValidationIdFixtureIdKindRouteImport } from './routes/api/template-artifacts/$validationId.$fixtureId.$kind'
import { Route as ApiTemplateProposalsTaskIdOperationIdKindRouteImport } from './routes/api/template-proposals/$taskId.$operationId.$kind'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckpointsCheckpointIdRoute = CheckpointsCheckpointIdRouteImport.update({
  id: '/checkpoints/$checkpointId',
  path: '/checkpoints/$checkpointId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs_/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumesResumeIdRoute = ResumesResumeIdRouteImport.update({
  id: '/resumes/$resumeId',
  path: '/resumes/$resumeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContextsRoute = ApiV1ContextsRouteImport.update({
  id: '/api/v1/contexts',
  path: '/api/v1/contexts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DuplicatesRoute = ApiV1DuplicatesRouteImport.update({
  id: '/api/v1/duplicates',
  path: '/api/v1/duplicates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EvidenceRoute = ApiV1EvidenceRouteImport.update({
  id: '/api/v1/evidence',
  path: '/api/v1/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1JobsRoute = ApiV1JobsRouteImport.update({
  id: '/api/v1/jobs',
  path: '/api/v1/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MeRoute = ApiV1MeRouteImport.update({
  id: '/api/v1/me',
  path: '/api/v1/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SourcesRoute = ApiV1SourcesRouteImport.update({
  id: '/api/v1/sources',
  path: '/api/v1/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiArtifactsOperationIdKindRoute =
  ApiArtifactsOperationIdKindRouteImport.update({
    id: '/api/artifacts/$operationId/$kind',
    path: '/api/artifacts/$operationId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1EvidenceClaimIdRoute = ApiV1EvidenceClaimIdRouteImport.update({
  id: '/$claimId',
  path: '/$claimId',
  getParentRoute: () => ApiV1EvidenceRoute,
} as any)
const ApiV1JobsJobIdRoute = ApiV1JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => ApiV1JobsRoute,
} as any)
const ApiV1SourcesSourceIdRoute = ApiV1SourcesSourceIdRouteImport.update({
  id: '/$sourceId',
  path: '/$sourceId',
  getParentRoute: () => ApiV1SourcesRoute,
} as any)
const ApiTemplateArtifactsValidationIdFixtureIdKindRoute =
  ApiTemplateArtifactsValidationIdFixtureIdKindRouteImport.update({
    id: '/api/template-artifacts/$validationId/$fixtureId/$kind',
    path: '/api/template-artifacts/$validationId/$fixtureId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTemplateProposalsTaskIdOperationIdKindRoute =
  ApiTemplateProposalsTaskIdOperationIdKindRouteImport.update({
    id: '/api/template-proposals/$taskId/$operationId/$kind',
    path: '/api/template-proposals/$taskId/$operationId/$kind',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/checkpoints/$checkpointId': typeof CheckpointsCheckpointIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/contexts': typeof ApiV1ContextsRoute
  '/api/v1/duplicates': typeof ApiV1DuplicatesRoute
  '/api/v1/evidence': typeof ApiV1EvidenceRouteWithChildren
  '/api/v1/jobs': typeof ApiV1JobsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sources': typeof ApiV1SourcesRouteWithChildren
  '/api/artifacts/$operationId/$kind': typeof ApiArtifactsOperationIdKindRoute
  '/api/v1/evidence/$claimId': typeof ApiV1EvidenceClaimIdRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
  '/api/template-artifacts/$validationId/$fixtureId/$kind': typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  '/api/template-proposals/$taskId/$operationId/$kind': typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/checkpoints/$checkpointId': typeof CheckpointsCheckpointIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/contexts': typeof ApiV1ContextsRoute
  '/api/v1/duplicates': typeof ApiV1DuplicatesRoute
  '/api/v1/evidence': typeof ApiV1EvidenceRouteWithChildren
  '/api/v1/jobs': typeof ApiV1JobsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sources': typeof ApiV1SourcesRouteWithChildren
  '/api/artifacts/$operationId/$kind': typeof ApiArtifactsOperationIdKindRoute
  '/api/v1/evidence/$claimId': typeof ApiV1EvidenceClaimIdRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
  '/api/template-artifacts/$validationId/$fixtureId/$kind': typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  '/api/template-proposals/$taskId/$operationId/$kind': typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceRoute
  '/jobs': typeof JobsRoute
  '/library': typeof LibraryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sources': typeof SourcesRoute
  '/templates': typeof TemplatesRoute
  '/checkpoints/$checkpointId': typeof CheckpointsCheckpointIdRoute
  '/jobs_/$jobId': typeof JobsJobIdRoute
  '/resumes/$resumeId': typeof ResumesResumeIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/contexts': typeof ApiV1ContextsRoute
  '/api/v1/duplicates': typeof ApiV1DuplicatesRoute
  '/api/v1/evidence': typeof ApiV1EvidenceRouteWithChildren
  '/api/v1/jobs': typeof ApiV1JobsRouteWithChildren
  '/api/v1/me': typeof ApiV1MeRoute
  '/api/v1/sources': typeof ApiV1SourcesRouteWithChildren
  '/api/artifacts/$operationId/$kind': typeof ApiArtifactsOperationIdKindRoute
  '/api/v1/evidence/$claimId': typeof ApiV1EvidenceClaimIdRoute
  '/api/v1/jobs/$jobId': typeof ApiV1JobsJobIdRoute
  '/api/v1/sources/$sourceId': typeof ApiV1SourcesSourceIdRoute
  '/api/template-artifacts/$validationId/$fixtureId/$kind': typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  '/api/template-proposals/$taskId/$operationId/$kind': typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evidence'
    | '/jobs'
    | '/library'
    | '/mcp'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sources'
    | '/templates'
    | '/checkpoints/$checkpointId'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/api/auth/$'
    | '/api/v1/contexts'
    | '/api/v1/duplicates'
    | '/api/v1/evidence'
    | '/api/v1/jobs'
    | '/api/v1/me'
    | '/api/v1/sources'
    | '/api/artifacts/$operationId/$kind'
    | '/api/v1/evidence/$claimId'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/sources/$sourceId'
    | '/api/template-artifacts/$validationId/$fixtureId/$kind'
    | '/api/template-proposals/$taskId/$operationId/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evidence'
    | '/jobs'
    | '/library'
    | '/mcp'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sources'
    | '/templates'
    | '/checkpoints/$checkpointId'
    | '/jobs/$jobId'
    | '/resumes/$resumeId'
    | '/api/auth/$'
    | '/api/v1/contexts'
    | '/api/v1/duplicates'
    | '/api/v1/evidence'
    | '/api/v1/jobs'
    | '/api/v1/me'
    | '/api/v1/sources'
    | '/api/artifacts/$operationId/$kind'
    | '/api/v1/evidence/$claimId'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/sources/$sourceId'
    | '/api/template-artifacts/$validationId/$fixtureId/$kind'
    | '/api/template-proposals/$taskId/$operationId/$kind'
  id:
    | '__root__'
    | '/'
    | '/evidence'
    | '/jobs'
    | '/library'
    | '/mcp'
    | '/reset-password'
    | '/settings'
    | '/sign-in'
    | '/sources'
    | '/templates'
    | '/checkpoints/$checkpointId'
    | '/jobs_/$jobId'
    | '/resumes/$resumeId'
    | '/api/auth/$'
    | '/api/v1/contexts'
    | '/api/v1/duplicates'
    | '/api/v1/evidence'
    | '/api/v1/jobs'
    | '/api/v1/me'
    | '/api/v1/sources'
    | '/api/artifacts/$operationId/$kind'
    | '/api/v1/evidence/$claimId'
    | '/api/v1/jobs/$jobId'
    | '/api/v1/sources/$sourceId'
    | '/api/template-artifacts/$validationId/$fixtureId/$kind'
    | '/api/template-proposals/$taskId/$operationId/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceRoute: typeof EvidenceRoute
  JobsRoute: typeof JobsRoute
  LibraryRoute: typeof LibraryRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SourcesRoute: typeof SourcesRoute
  TemplatesRoute: typeof TemplatesRoute
  CheckpointsCheckpointIdRoute: typeof CheckpointsCheckpointIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  ResumesResumeIdRoute: typeof ResumesResumeIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1ContextsRoute: typeof ApiV1ContextsRoute
  ApiV1DuplicatesRoute: typeof ApiV1DuplicatesRoute
  ApiV1EvidenceRoute: typeof ApiV1EvidenceRouteWithChildren
  ApiV1JobsRoute: typeof ApiV1JobsRouteWithChildren
  ApiV1MeRoute: typeof ApiV1MeRoute
  ApiV1SourcesRoute: typeof ApiV1SourcesRouteWithChildren
  ApiArtifactsOperationIdKindRoute: typeof ApiArtifactsOperationIdKindRoute
  ApiTemplateArtifactsValidationIdFixtureIdKindRoute: typeof ApiTemplateArtifactsValidationIdFixtureIdKindRoute
  ApiTemplateProposalsTaskIdOperationIdKindRoute: typeof ApiTemplateProposalsTaskIdOperationIdKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkpoints/$checkpointId': {
      id: '/checkpoints/$checkpointId'
      path: '/checkpoints/$checkpointId'
      fullPath: '/checkpoints/$checkpointId'
      preLoaderRoute: typeof CheckpointsCheckpointIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs_/$jobId': {
      id: '/jobs_/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resumes/$resumeId': {
      id: '/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof ResumesResumeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contexts': {
      id: '/api/v1/contexts'
      path: '/api/v1/contexts'
      fullPath: '/api/v1/contexts'
      preLoaderRoute: typeof ApiV1ContextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/duplicates': {
      id: '/api/v1/duplicates'
      path: '/api/v1/duplicates'
      fullPath: '/api/v1/duplicates'
      preLoaderRoute: typeof ApiV1DuplicatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evidence': {
      id: '/api/v1/evidence'
      path: '/api/v1/evidence'
      fullPath: '/api/v1/evidence'
      preLoaderRoute: typeof ApiV1EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/jobs': {
      id: '/api/v1/jobs'
      path: '/api/v1/jobs'
      fullPath: '/api/v1/jobs'
      preLoaderRoute: typeof ApiV1JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/me': {
      id: '/api/v1/me'
      path: '/api/v1/me'
      fullPath: '/api/v1/me'
      preLoaderRoute: typeof ApiV1MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/sources': {
      id: '/api/v1/sources'
      path: '/api/v1/sources'
      fullPath: '/api/v1/sources'
      preLoaderRoute: typeof ApiV1SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/artifacts/$operationId/$kind': {
      id: '/api/artifacts/$operationId/$kind'
      path: '/api/artifacts/$operationId/$kind'
      fullPath: '/api/artifacts/$operationId/$kind'
      preLoaderRoute: typeof ApiArtifactsOperationIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/evidence/$claimId': {
      id: '/api/v1/evidence/$claimId'
      path: '/$claimId'
      fullPath: '/api/v1/evidence/$claimId'
      preLoaderRoute: typeof ApiV1EvidenceClaimIdRouteImport
      parentRoute: typeof ApiV1EvidenceRoute
    }
    '/api/v1/jobs/$jobId': {
      id: '/api/v1/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/api/v1/jobs/$jobId'
      preLoaderRoute: typeof ApiV1JobsJobIdRouteImport
      parentRoute: typeof ApiV1JobsRoute
    }
    '/api/v1/sources/$sourceId': {
      id: '/api/v1/sources/$sourceId'
      path: '/$sourceId'
      fullPath: '/api/v1/sources/$sourceId'
      preLoaderRoute: typeof ApiV1SourcesSourceIdRouteImport
      parentRoute: typeof ApiV1SourcesRoute
    }
    '/api/template-artifacts/$validationId/$fixtureId/$kind': {
      id: '/api/template-artifacts/$validationId/$fixtureId/$kind'
      path: '/api/template-artifacts/$validationId/$fixtureId/$kind'
      fullPath: '/api/template-artifacts/$validationId/$fixtureId/$kind'
      preLoaderRoute: typeof ApiTemplateArtifactsValidationIdFixtureIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/template-proposals/$taskId/$operationId/$kind': {
      id: '/api/template-proposals/$taskId/$operationId/$kind'
      path: '/api/template-proposals/$taskId/$operationId/$kind'
      fullPath: '/api/template-proposals/$taskId/$operationId/$kind'
      preLoaderRoute: typeof ApiTemplateProposalsTaskIdOperationIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiV1EvidenceRouteChildren {
  ApiV1EvidenceClaimIdRoute: typeof ApiV1EvidenceClaimIdRoute
}

const ApiV1EvidenceRouteChildren: ApiV1EvidenceRouteChildren = {
  ApiV1EvidenceClaimIdRoute: ApiV1EvidenceClaimIdRoute,
}

const ApiV1EvidenceRouteWithChildren = ApiV1EvidenceRoute._addFileChildren(
  ApiV1EvidenceRouteChildren,
)

interface ApiV1JobsRouteChildren {
  ApiV1JobsJobIdRoute: typeof ApiV1JobsJobIdRoute
}

const ApiV1JobsRouteChildren: ApiV1JobsRouteChildren = {
  ApiV1JobsJobIdRoute: ApiV1JobsJobIdRoute,
}

const ApiV1JobsRouteWithChildren = ApiV1JobsRoute._addFileChildren(
  ApiV1JobsRouteChildren,
)

interface ApiV1SourcesRouteChildren {
  ApiV1SourcesSourceIdRoute: typeof ApiV1SourcesSourceIdRoute
}

const ApiV1SourcesRouteChildren: ApiV1SourcesRouteChildren = {
  ApiV1SourcesSourceIdRoute: ApiV1SourcesSourceIdRoute,
}

const ApiV1SourcesRouteWithChildren = ApiV1SourcesRoute._addFileChildren(
  ApiV1SourcesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceRoute: EvidenceRoute,
  JobsRoute: JobsRoute,
  LibraryRoute: LibraryRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SourcesRoute: SourcesRoute,
  TemplatesRoute: TemplatesRoute,
  CheckpointsCheckpointIdRoute: CheckpointsCheckpointIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  ResumesResumeIdRoute: ResumesResumeIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1ContextsRoute: ApiV1ContextsRoute,
  ApiV1DuplicatesRoute: ApiV1DuplicatesRoute,
  ApiV1EvidenceRoute: ApiV1EvidenceRouteWithChildren,
  ApiV1JobsRoute: ApiV1JobsRouteWithChildren,
  ApiV1MeRoute: ApiV1MeRoute,
  ApiV1SourcesRoute: ApiV1SourcesRouteWithChildren,
  ApiArtifactsOperationIdKindRoute: ApiArtifactsOperationIdKindRoute,
  ApiTemplateArtifactsValidationIdFixtureIdKindRoute:
    ApiTemplateArtifactsValidationIdFixtureIdKindRoute,
  ApiTemplateProposalsTaskIdOperationIdKindRoute:
    ApiTemplateProposalsTaskIdOperationIdKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
